# Generated by Django 3.0.7 on 2020-06-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Risk_project_ufps', '0002_delete_proyectos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
    ]
