# Generated by Django 3.0.7 on 2020-07-02 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Risk_project_ufps', '0004_auto_20200701_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerentes',
            name='usuario',
            field=models.EmailField(max_length=254, verbose_name='Correo electronico'),
        ),
    ]
