# Generated by Django 3.0.7 on 2020-07-27 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Risk_project_ufps', '0006_categorias_subcategorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Riesgos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('causa', models.CharField(blank=True, max_length=100, null=True)),
                ('efecto', models.CharField(blank=True, max_length=100, null=True)),
                ('evento', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=12, null=True)),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Risk_project_ufps.Subcategorias')),
            ],
        ),
    ]
