# Generated by Django 3.0.8 on 2020-08-16 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Risk_project_ufps', '0007_riesgos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('categoria_descripcion', models.TextField(blank=True, null=True)),
                ('categoria_uid', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('gerente_id', models.AutoField(primary_key=True, serialize=False)),
                ('gerente_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('gerente_usuario', models.CharField(max_length=45, unique=True)),
                ('gerente_correo', models.CharField(blank=True, max_length=100, null=True)),
                ('gerente_fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('gerente_profesion', models.CharField(blank=True, max_length=100, null=True)),
                ('gerente_empresa', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'gerente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('proyecto_id', models.AutoField(primary_key=True, serialize=False)),
                ('proyecto_nombre', models.CharField(max_length=100)),
                ('proyecto_objetivo', models.TextField(blank=True, null=True)),
                ('proyecto_alcance', models.TextField(blank=True, null=True)),
                ('proyecto_descripcion', models.TextField(blank=True, null=True)),
                ('proyecto_presupuesto', models.FloatField(blank=True, null=True)),
                ('proyecto_fecha_inicio', models.DateField(blank=True, null=True)),
                ('proyecto_fecha_finl', models.DateField(blank=True, null=True)),
                ('proyecto_evaluacion_general', models.TextField(blank=True, null=True)),
                ('proyecto_evaluacion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'proyecto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rbs',
            fields=[
                ('rbs_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'rbs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('recurso_id', models.AutoField(primary_key=True, serialize=False)),
                ('recurso_nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('recurso_costo', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recurso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('respuesta_id', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta_nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('respuesta_descripcion', models.TextField(blank=True, null=True)),
                ('respuesta_costo', models.FloatField(blank=True, null=True)),
                ('respuesta_fecha_respuesta', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'respuesta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('riesgo_id', models.AutoField(primary_key=True, serialize=False)),
                ('riesgo_nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('riesgo_causa', models.TextField(blank=True, null=True)),
                ('riesgo_evento', models.TextField(blank=True, null=True)),
                ('riesgo_efecto', models.TextField(blank=True, null=True)),
                ('riesgo_tipo', models.IntegerField(blank=True, null=True)),
                ('riesgo_prom_evaluacion', models.FloatField(blank=True, null=True)),
                ('riesgo_privacidad', models.IntegerField()),
                ('riesgo_uid', models.BigIntegerField(blank=True)),
                ('riesgo_fecha_manifestacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'riesgo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('sector_id', models.AutoField(primary_key=True, serialize=False)),
                ('sector_nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'sector',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('sub_categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_categoria_nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('sub_categoria_descripcion', models.TextField(blank=True, null=True)),
                ('sub_categoria_uid', models.BigIntegerField(unique=True)),
            ],
            options={
                'db_table': 'sub_categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('tipo_recurso_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_recurso_nombre', models.CharField(max_length=45)),
                ('tipo_recurso_descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tipo_recurso',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Gerentes',
        ),
        migrations.DeleteModel(
            name='Proyectos',
        ),
        migrations.RemoveField(
            model_name='riesgos',
            name='subcategoria',
        ),
        migrations.RemoveField(
            model_name='subcategorias',
            name='categoria',
        ),
        migrations.CreateModel(
            name='ProyectoHasRiesgo',
            fields=[
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Risk_project_ufps.Proyecto')),
            ],
            options={
                'db_table': 'proyecto_has_riesgo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RespuestaHasRecurso',
            fields=[
                ('respuesta', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Risk_project_ufps.Respuesta')),
            ],
            options={
                'db_table': 'respuesta_has_recurso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RiesgoHasRespuesta',
            fields=[
                ('riesgo', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Risk_project_ufps.Riesgo')),
            ],
            options={
                'db_table': 'riesgo_has_respuesta',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
        migrations.DeleteModel(
            name='Riesgos',
        ),
        migrations.DeleteModel(
            name='Subcategorias',
        ),
    ]
